### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by elboletaire** [SuneBear/Piano-Flow#3]
If you don't plan to add firefox support, at least mention it on the readme :)

Checked under firefox developer edition [version 52.0a2 (2016-11-27) (64 bits)] and under firefox for Android (latest available version in play store).

**Comment by SuneBear** [comment]
Thanks for your feedback, I will verify and fix compatibility for Firefox in this weekend.

FYI: [README#browser-compatibility](https://github.com/SuneBear/Piano-Flow#browser-compatibility)

**Comment by elboletaire** [comment]
> FYI: [README#browser-compatibility](https://github.com/SuneBear/Piano-Flow#browser-compatibility)

Thanks, didn't see that notice.

**Comment by SuneBear** [comment]
@elboletaire Happy to tell you that I fixed the compatibility issue. Refer to:
> [ISSUE(theme): Fixed getPropertyValue in FF, replaced borderColor with borderLeftColor#L20~22](https://github.com/SuneBear/Piano-Flow/commit/949e3b2784f32f2f723c797d30687c1d9272be2b#diff-e1c6d5d34fa2955dc0df3284a194bce3L19)

[The bug](https://bugzilla.mozilla.org/show_bug.cgi?id=137688) was reported to Bugzilla  when I was in elementary school 14 years ago, FF still no plan to resolve it...

**Comment by elboletaire** [comment]
Then why not close the issue? 😃 

PS. Checked that it works on firefox, so I'll close it for you ;p

**Comment by elboletaire** [comment]
Oh, and excellent work with the app!

**Comment by SuneBear** [comment]
XD, I thought that need your confirmation, glad to see you closed it.
